;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Cum Mar 11 2016
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
STAK    SEGMENT PARA STACK 'STACK'
        DW 20 DUP(?)
STAK    ENDS

DATA    SEGMENT PARA 'DATA'
DIGITS  DB 00H
DATA    ENDS

CODE    SEGMENT PARA 'CODE'
        ASSUME CS:CODE, DS:DATA, SS:STAK
START:
        MOV AX, DATA
	MOV DS, AX
	
	MOV DX, 020Ah
	MOV AL, 01001101B
	OUT DX, AL
	
	MOV AL, 40H
	OUT DX, AL
	
	MOV AL, 01001101B
	OUT DX, AL
	
	MOV AL, 00010101B
	OUT DX, AL
	

ENDLESS:

	MOV DX, 020AH
TEKRAR:
	IN AL, DX
	AND AL, 02H
	JZ TEKRAR
	
	MOV DX, 0208H
	IN AL, DX
	INC AL
	
	
	MOV BL, AL
	
	MOV DX, 020AH
TEKRAR2:
	IN AL, DX
	AND AL, 01H
	JZ TEKRAR2
	
	MOV DX, 0208H
	MOV AL, BL
	OUT DX, AL

	
        JMP ENDLESS
CODE    ENDS
        END START